version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"     # Jenkins UI
      - "50000:50000"   # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      # If you want to map a local directory, replace with:
      # - ./jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:

